//! 字体库「推荐」里的字体。
//!
//! 条目从 XGCut 那份核过协议原文的目录里挑出来，按我们的三种用途重新分组：
//! 做游戏、剪视频、PS 做图。一款字可以出现在好几个用途里（得意黑既是游戏标题也是视频封面）。
//!
//! 收录标准照旧：协议必须是开源协议（OFL 为主，霞鹜新晰黑是 IPA），
//! 而且能在项目仓库里点开协议原文。厂商「声明免费商用」但没有开源协议的不收。
//!
//! 下面几个字段不是手写的，是拿字体文件本身量出来的（scripts/make-font-previews.py
//! 用的也是同一批文件）：
//!
//! - `families`：装好之后系统里的英文族名。拿它认「本机已经装过了」
//! - `px`：像素字的原生字号。把几个字形的轮廓坐标求最大公约数就是一个「像素」多大，
//!   em 除以它就是网格对齐的字号 —— 只有在它的整数倍上才是清清楚楚的方块
//! - `sc` `tc` `kana` `latin`：cmap 里真的有简体 / 繁体 / 假名 / 西文

use serde::Serialize;

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Pack {
    pub id: &'static str,
    /// 中文名
    pub name: &'static str,
    /// 原名
    pub latin: &'static str,
    /// 一句话：长什么样、适合干嘛
    pub note: &'static str,
    /// 放在哪几个用途小类里，见 USES
    pub uses: &'static [&'static str],
    pub license: &'static str,
    /// 协议原文（点开能直接看条款）
    pub license_url: &'static str,
    pub home: &'static str,
    pub url: &'static str,
    /// 下载包大概多大（MB）
    pub size_mb: u32,
    pub families: &'static [&'static str],
    pub px: &'static [u16],
    pub sc: bool,
    pub tc: bool,
    pub kana: bool,
    pub latin_ok: bool,
    /// 压缩包里一套字给了好几种语言版本时，只装名字里带这个的那份；空 = 全装
    pub pick: &'static str,
}

/// 用途小类。前端按这个顺序排左边的分类栏
pub const USES: &[&str] = &[
    "game-pixel", "game-ui", "game-title",
    "video-sub", "video-cover", "video-title",
    "ps-brush", "ps-serif", "ps-latin",
];

const GF: &str = "https://github.com/google/fonts/blob/main/ofl";

macro_rules! gf_license {
    ($dir:literal) => {
        concat!("https://github.com/google/fonts/blob/main/ofl/", $dir, "/OFL.txt")
    };
}

pub const CATALOG: &[Pack] = &[
    // ── 游戏 · 像素 ──
    Pack {
        id: "cubic-11",
        name: "俐方体 11 号",
        latin: "Cubic 11",
        note: "中文点阵体，横平竖直，像素游戏的对话和菜单最合适",
        uses: &["game-pixel"],
        license: "OFL",
        license_url: "https://github.com/ACh-K/Cubic-11/blob/main/OFL.txt",
        home: "https://github.com/ACh-K/Cubic-11",
        url: "https://github.com/ACh-K/Cubic-11/raw/main/fonts/ttf/Cubic_11.ttf",
        size_mb: 3,
        families: &["Cubic 11"],
        px: &[12],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "ark-pixel-12",
        name: "方舟像素",
        latin: "Ark Pixel 12px",
        note: "12 像素的泛中日韩点阵体，字数极全，像素游戏的中文界面首选",
        uses: &["game-pixel"],
        license: "OFL",
        license_url: "https://github.com/TakWolf/ark-pixel-font/blob/master/LICENSE-OFL",
        home: "https://github.com/TakWolf/ark-pixel-font",
        url: "https://github.com/TakWolf/ark-pixel-font/releases/download/2026.09.01/ark-pixel-font-12px-proportional-otf-v2026.09.01.zip",
        size_mb: 23,
        families: &["Ark Pixel 12px Prop zh_cn"],
        px: &[12],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "zh_cn",
    },
    Pack {
        id: "fusion-pixel-12",
        name: "缝合像素",
        latin: "Fusion Pixel 12px",
        note: "拿方舟像素当底子，再用别的开源像素字补齐缺字，要字全就用它",
        uses: &["game-pixel"],
        license: "OFL",
        license_url: "https://github.com/TakWolf/fusion-pixel-font/blob/master/LICENSE-OFL",
        home: "https://github.com/TakWolf/fusion-pixel-font",
        url: "https://github.com/TakWolf/fusion-pixel-font/releases/download/2026.09.01/fusion-pixel-font-12px-proportional-otf-v2026.09.01.zip",
        size_mb: 23,
        families: &["Fusion Pixel 12px Prop zh_hans"],
        px: &[12],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "zh_hans",
    },
    Pack {
        id: "chill-bitmap",
        name: "寒蝉点阵体",
        latin: "ChillBitmap",
        note: "另一套中文点阵，大小两种：8 像素的做血条旁的小字，16 像素的做对话",
        uses: &["game-pixel"],
        license: "OFL",
        license_url: "https://github.com/Warren2060/ChillBitmap/blob/main/LICENSE.md",
        home: "https://github.com/Warren2060/ChillBitmap",
        url: "https://github.com/Warren2060/ChillBitmap/releases/download/v2.502/ChillBitmap_New.zip",
        size_mb: 4,
        families: &["ChillBitmap", "寒蝉点阵体"],
        px: &[8, 16],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "dotgothic16",
        name: "点阵哥特",
        latin: "DotGothic16",
        note: "日文点阵体，假名齐全，和风像素游戏很对味；简体中文缺不少字",
        uses: &["game-pixel"],
        license: "OFL",
        license_url: gf_license!("dotgothic16"),
        home: "https://fonts.google.com/specimen/DotGothic16",
        url: "https://github.com/google/fonts/raw/main/ofl/dotgothic16/DotGothic16-Regular.ttf",
        size_mb: 2,
        families: &["DotGothic16"],
        px: &[],
        sc: false, tc: false, kana: true, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "press-start-2p",
        name: "红白机",
        latin: "Press Start 2P",
        note: "街机和红白机那种方块英文，标题画面和分数板一秒回到八十年代",
        uses: &["game-pixel"],
        license: "OFL",
        license_url: gf_license!("pressstart2p"),
        home: "https://fonts.google.com/specimen/Press+Start+2P",
        url: "https://github.com/google/fonts/raw/main/ofl/pressstart2p/PressStart2P-Regular.ttf",
        size_mb: 1,
        families: &["Press Start 2P"],
        px: &[8],
        sc: false, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "silkscreen",
        name: "丝网印",
        latin: "Silkscreen",
        note: "极小号的像素英文，游戏 UI 标签和血条数字最合适",
        uses: &["game-pixel"],
        license: "OFL",
        license_url: gf_license!("silkscreen"),
        home: "https://fonts.google.com/specimen/Silkscreen",
        url: "https://github.com/google/fonts/raw/main/ofl/silkscreen/Silkscreen-Regular.ttf",
        size_mb: 1,
        families: &["Silkscreen"],
        px: &[],
        sc: false, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "jersey25",
        name: "球衣 25",
        latin: "Jersey 25",
        note: "球衣号码那种粗像素，比分、计时器、大数字很带劲",
        uses: &["game-pixel"],
        license: "OFL",
        license_url: gf_license!("jersey25"),
        home: "https://fonts.google.com/specimen/Jersey+25",
        url: "https://github.com/google/fonts/raw/main/ofl/jersey25/Jersey25-Regular.ttf",
        size_mb: 1,
        families: &["Jersey 25"],
        px: &[],
        sc: false, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    // ── 游戏 · 界面和对话 ──
    Pack {
        id: "source-han-sans-sc",
        name: "思源黑体",
        latin: "Source Han Sans SC",
        note: "Adobe 和 Google 合作的黑体，七个字重齐全，界面和字幕最稳妥的选择",
        uses: &["game-ui", "video-sub"],
        license: "OFL",
        license_url: "https://github.com/adobe-fonts/source-han-sans/blob/master/LICENSE.txt",
        home: "https://github.com/adobe-fonts/source-han-sans",
        url: "https://github.com/adobe-fonts/source-han-sans/releases/download/2.005R/09_SourceHanSansSC.zip",
        size_mb: 90,
        families: &["Source Han Sans SC"],
        px: &[],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "chill-round",
        name: "寒蝉圆黑体",
        latin: "ChillRound Gothic",
        note: "圆角黑体，游戏 UI 和儿童向内容最爱用的那一挂",
        uses: &["game-ui"],
        license: "OFL",
        license_url: "https://github.com/Warren2060/ChillRound/blob/main/LICENSE",
        home: "https://github.com/Warren2060/ChillRound",
        url: "https://github.com/Warren2060/ChillRound/releases/download/v1.805/ChillRoundM_v1.805.zip",
        size_mb: 7,
        families: &["ChillRoundM"],
        px: &[],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "glow-sans-sc",
        name: "未来荧黑",
        latin: "Glow Sans SC",
        note: "带一点未来感的现代黑体，九个字重，科幻、电竞题材的界面很好看",
        uses: &["game-ui"],
        license: "OFL",
        license_url: "https://github.com/welai/glow-sans/blob/master/OFL.txt",
        home: "https://github.com/welai/glow-sans",
        url: "https://github.com/welai/glow-sans/releases/download/v0.93/GlowSansSC-Normal-v0.93.zip",
        size_mb: 64,
        families: &["Glow Sans SC"],
        px: &[],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "",
    },
    // ── 游戏 · 标题 ──
    Pack {
        id: "smiley-sans",
        name: "得意黑",
        latin: "Smiley Sans",
        note: "倾斜的浓缩黑体，游戏 logo 和视频封面都很抢眼",
        uses: &["game-title", "video-cover"],
        license: "OFL",
        license_url: "https://github.com/atelier-anchor/smiley-sans/blob/main/LICENSE",
        home: "https://github.com/atelier-anchor/smiley-sans",
        url: "https://github.com/atelier-anchor/smiley-sans/releases/download/v2.0.1/smiley-sans-v2.0.1.zip",
        size_mb: 5,
        families: &["Smiley Sans"],
        px: &[],
        sc: true, tc: false, kana: true, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "orbitron",
        name: "轨道体",
        latin: "Orbitron",
        note: "科幻感的几何体，太空、机甲、电竞标题的老牌选择",
        uses: &["game-title"],
        license: "OFL",
        license_url: gf_license!("orbitron"),
        home: "https://fonts.google.com/specimen/Orbitron",
        url: "https://github.com/google/fonts/raw/main/ofl/orbitron/Orbitron%5Bwght%5D.ttf",
        size_mb: 1,
        families: &["Orbitron"],
        px: &[],
        sc: false, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "audiowide",
        name: "宽音体",
        latin: "Audiowide",
        note: "带电路板味道的宽体，游戏 logo 和赛博标题常客",
        uses: &["game-title"],
        license: "OFL",
        license_url: gf_license!("audiowide"),
        home: "https://fonts.google.com/specimen/Audiowide",
        url: "https://github.com/google/fonts/raw/main/ofl/audiowide/Audiowide-Regular.ttf",
        size_mb: 1,
        families: &["Audiowide"],
        px: &[],
        sc: false, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    // ── 剪辑 · 字幕 ──
    Pack {
        id: "lxgw-wenkai",
        name: "霞鹜文楷",
        latin: "LXGW WenKai",
        note: "手写感的楷体，字幕和正文都耐看，中文开源字体里的头牌",
        uses: &["video-sub"],
        license: "OFL",
        license_url: "https://github.com/lxgw/LxgwWenKai/blob/main/OFL.txt",
        home: "https://github.com/lxgw/LxgwWenKai",
        url: "https://github.com/lxgw/LxgwWenKai/releases/latest/download/LXGWWenKai-Regular.ttf",
        size_mb: 24,
        families: &["LXGW WenKai"],
        px: &[],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "lxgw-neo-xihei",
        name: "霞鹜新晰黑",
        latin: "LXGW Neo XiHei",
        note: "清爽的细黑体，字幕压在画面上也不显重",
        uses: &["video-sub"],
        license: "IPA",
        license_url: "https://github.com/lxgw/LxgwNeoXiHei/blob/main/LICENSE.md",
        home: "https://github.com/lxgw/LxgwNeoXiHei",
        url: "https://github.com/lxgw/LxgwNeoXiHei/releases/latest/download/LXGWNeoXiHei.ttf",
        size_mb: 7,
        families: &["LXGW Neo XiHei"],
        px: &[],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "",
    },
    // ── 剪辑 · 封面和花字 ──
    Pack {
        id: "zcool-qingke",
        name: "站酷庆科黄油体",
        latin: "ZCOOL QingKe HuangYou",
        note: "厚重可爱，综艺花字、封面大标题压在画面上很扎实",
        uses: &["video-cover"],
        license: "OFL",
        license_url: gf_license!("zcoolqingkehuangyou"),
        home: "https://fonts.google.com/specimen/ZCOOL+QingKe+HuangYou",
        url: "https://github.com/google/fonts/raw/main/ofl/zcoolqingkehuangyou/ZCOOLQingKeHuangYou-Regular.ttf",
        size_mb: 8,
        families: &["ZCOOL QingKe HuangYou"],
        px: &[],
        sc: true, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "zcool-kuaile",
        name: "站酷快乐体",
        latin: "ZCOOL KuaiLe",
        note: "圆润卡通，轻松题材的花字和贴纸字百搭",
        uses: &["video-cover"],
        license: "OFL",
        license_url: gf_license!("zcoolkuaile"),
        home: "https://fonts.google.com/specimen/ZCOOL+KuaiLe",
        url: "https://github.com/google/fonts/raw/main/ofl/zcoolkuaile/ZCOOLKuaiLe-Regular.ttf",
        size_mb: 2,
        families: &["ZCOOL KuaiLe"],
        px: &[],
        sc: true, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "lxgw-marker",
        name: "霞鹜漫黑",
        latin: "LXGW Marker Gothic",
        note: "马克笔写出来的手绘黑体，吐槽字幕和手账风标题很自然",
        uses: &["video-cover"],
        license: "OFL",
        license_url: "https://github.com/lxgw/LxgwMarkerGothic/blob/main/OFL.txt",
        home: "https://github.com/lxgw/LxgwMarkerGothic",
        url: "https://github.com/lxgw/LxgwMarkerGothic/releases/download/v1.003/LxgwMarkerGothic-v1.003.zip",
        size_mb: 4,
        families: &["LXGW Marker Gothic"],
        px: &[],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "",
    },
    // ── 剪辑 · 片头题字 / PS · 书法 ──
    Pack {
        id: "ma-shan-zheng",
        name: "马善政毛笔楷书",
        latin: "Ma Shan Zheng",
        note: "毛笔写的楷书，起收笔看得见锋，片头题字很正",
        uses: &["video-title", "ps-brush"],
        license: "OFL",
        license_url: gf_license!("mashanzheng"),
        home: "https://fonts.google.com/specimen/Ma+Shan+Zheng",
        url: "https://github.com/google/fonts/raw/main/ofl/mashanzheng/MaShanZheng-Regular.ttf",
        size_mb: 6,
        families: &["Ma Shan Zheng"],
        px: &[],
        sc: true, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "zhi-mang-xing",
        name: "志莽行书",
        latin: "Zhi Mang Xing",
        note: "连笔行书，写得快、带点野气，适合有情绪的短句",
        uses: &["video-title", "ps-brush"],
        license: "OFL",
        license_url: gf_license!("zhimangxing"),
        home: "https://fonts.google.com/specimen/Zhi+Mang+Xing",
        url: "https://github.com/google/fonts/raw/main/ofl/zhimangxing/ZhiMangXing-Regular.ttf",
        size_mb: 4,
        families: &["Zhi Mang Xing"],
        px: &[],
        sc: true, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "long-cang",
        name: "龙藏体",
        latin: "Long Cang",
        note: "细笔行书，松散随意，像随手写在纸上的字",
        uses: &["ps-brush"],
        license: "OFL",
        license_url: gf_license!("longcang"),
        home: "https://fonts.google.com/specimen/Long+Cang",
        url: "https://github.com/google/fonts/raw/main/ofl/longcang/LongCang-Regular.ttf",
        size_mb: 5,
        families: &["Long Cang"],
        px: &[],
        sc: true, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "liu-jian-mao-cao",
        name: "柳建毛草",
        latin: "Liu Jian Mao Cao",
        note: "草书，笔画连成一片，气势足但认读性弱，只适合少量字",
        uses: &["ps-brush"],
        license: "OFL",
        license_url: gf_license!("liujianmaocao"),
        home: "https://fonts.google.com/specimen/Liu+Jian+Mao+Cao",
        url: "https://github.com/google/fonts/raw/main/ofl/liujianmaocao/LiuJianMaoCao-Regular.ttf",
        size_mb: 5,
        families: &["Liu Jian Mao Cao"],
        px: &[],
        sc: true, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    // ── PS · 宋体排版 ──
    Pack {
        id: "source-han-serif-cn",
        name: "思源宋体",
        latin: "Source Han Serif CN",
        note: "正统宋体，七个字重，海报正文和引文很稳",
        uses: &["ps-serif"],
        license: "OFL",
        license_url: "https://github.com/adobe-fonts/source-han-serif/blob/master/LICENSE.txt",
        home: "https://github.com/adobe-fonts/source-han-serif",
        url: "https://github.com/adobe-fonts/source-han-serif/releases/download/2.003R/14_SourceHanSerifCN.zip",
        size_mb: 65,
        families: &["Source Han Serif CN"],
        px: &[],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "cactus-classical",
        name: "仙人掌明体",
        latin: "Cactus Classical Serif",
        note: "台湾做的古典明体，横细竖粗、笔锋清楚，古风海报很正",
        uses: &["ps-serif"],
        license: "OFL",
        license_url: gf_license!("cactusclassicalserif"),
        home: "https://fonts.google.com/specimen/Cactus+Classical+Serif",
        url: "https://github.com/google/fonts/raw/main/ofl/cactusclassicalserif/CactusClassicalSerif-Regular.ttf",
        size_mb: 28,
        families: &["Cactus Classical Serif"],
        px: &[],
        sc: true, tc: true, kana: true, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "zcool-xiaowei",
        name: "站酷小薇",
        latin: "ZCOOL XiaoWei",
        note: "宋楷之间，笔画细、有装饰感，标题用显得文气",
        uses: &["ps-serif"],
        license: "OFL",
        license_url: gf_license!("zcoolxiaowei"),
        home: "https://fonts.google.com/specimen/ZCOOL+XiaoWei",
        url: "https://github.com/google/fonts/raw/main/ofl/zcoolxiaowei/ZCOOLXiaoWei-Regular.ttf",
        size_mb: 6,
        families: &["ZCOOL XiaoWei"],
        px: &[],
        sc: true, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    // ── PS · 西文标题 ──
    Pack {
        id: "russo-one",
        name: "俄式方体",
        latin: "Russo One",
        note: "又粗又方的斯拉夫风标题体，压在画面上很有力",
        uses: &["ps-latin"],
        license: "OFL",
        license_url: gf_license!("russoone"),
        home: "https://fonts.google.com/specimen/Russo+One",
        url: "https://github.com/google/fonts/raw/main/ofl/russoone/RussoOne-Regular.ttf",
        size_mb: 1,
        families: &["Russo One"],
        px: &[],
        sc: false, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "bungee",
        name: "招牌体",
        latin: "Bungee",
        note: "美式招牌字，专门为竖排设计过，街头风海报很合适",
        uses: &["ps-latin"],
        license: "OFL",
        license_url: gf_license!("bungee"),
        home: "https://fonts.google.com/specimen/Bungee",
        url: "https://github.com/google/fonts/raw/main/ofl/bungee/Bungee-Regular.ttf",
        size_mb: 1,
        families: &["Bungee"],
        px: &[],
        sc: false, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
    Pack {
        id: "space-grotesk",
        name: "太空怪诞",
        latin: "Space Grotesk",
        note: "有点复古又有点未来的无衬线，做科技类海报不落俗套",
        uses: &["ps-latin"],
        license: "OFL",
        license_url: gf_license!("spacegrotesk"),
        home: "https://fonts.google.com/specimen/Space+Grotesk",
        url: "https://github.com/google/fonts/raw/main/ofl/spacegrotesk/SpaceGrotesk%5Bwght%5D.ttf",
        size_mb: 1,
        families: &["Space Grotesk"],
        px: &[],
        sc: false, tc: false, kana: false, latin_ok: true,
        pick: "",
    },
];

pub fn find(id: &str) -> Option<&'static Pack> {
    CATALOG.iter().find(|p| p.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_is_consistent() {
        let mut ids = std::collections::HashSet::new();
        for p in CATALOG {
            assert!(ids.insert(p.id), "id 重复: {}", p.id);
            assert!(!p.uses.is_empty(), "{} 没放进任何用途", p.id);
            for u in p.uses {
                assert!(USES.contains(u), "{} 的用途 {u} 不在 USES 里", p.id);
            }
            assert!(p.url.starts_with("https://github.com/"), "{} 下载地址不在 GitHub", p.id);
            assert!(p.license_url.starts_with("https://"), "{} 缺协议原文", p.id);
            assert!(!p.families.is_empty(), "{} 没写族名", p.id);
        }
        // 每个用途小类都至少有一款
        for u in USES {
            assert!(CATALOG.iter().any(|p| p.uses.contains(u)), "用途 {u} 是空的");
        }
        let _ = GF;
    }
}
